version: "3.10"
   
services:
  web:
    image: shopping-tool
    command: gunicorn wsgi:app -c ./gunicorn.conf.py
    volumes:
      - .:/code
    ports:
      - "8001:8001"

  selenium:
    image: selenium/standalone-chrome
    ports:
    - 4444:4444