version: "3.10"
   
services:
  web:
    image: shopping-tool:v1.1.0
    command: gunicorn wsgi:app -c ./gunicorn.conf.py
    volumes:
      - .:/app
    ports:
      - "8001:8001"

  selenium:
    image: selenium/standalone-chrome
    ports:
    - 4444:4444
    shm_size: '500mb'
